name: highin_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter

  #Google_Sign-In
  firebase_auth: ^3.3.18
  google_sign_in: ^5.3.2

  #Google Icon
  font_awesome_flutter: ^10.1.0

  #State Management
  provider: ^6.0.3

  #Cloud Functions
  cloud_functions: ^3.2.15

  #Http Requests
  http: ^0.13.4

  #Firebase Core
  firebase_core: ^1.17.0

  #Image Picker
  image_picker: ^0.8.5+3

  #uuid
  uuid: ^3.0.6

  #SVG Image
  flutter_svg: ^1.1.0

  path_provider: ^2.0.10

  # flutter_staggered_grid_view: ^0.6.1
  flutter_staggered_grid_view: ^0.4.1

dev_dependencies:
  cloud_firestore: ^3.1.16
  firebase_storage: ^10.2.16
  flutter_lints: ^2.0.1
  flutter_svg: ^1.1.0
  flutter_test:
    sdk: flutter
  image_picker: ^0.8.5+3

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/ic_instagram.svg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
